title: ID Vision Docs
description: Official documentation for ID Vision system.

remote_theme: "jekyll/minima@1e8a445"

plugins:
  - jekyll-remote-theme

minima:
  skin: dark
  nav_enabled: false
  nav_pages: []
  footer_pages:
    - about.md
