theme: minima
title: ID Vision Docs
description: Official documentation for ID Vision system.

minima:
  skin: dark
  # غیرفعال کردن ناوبری
  navigation_links: []
  social_links: {}

# حذف کامل نوار ناوبری
header_pages: []
