title: ID Vision Docs
description: Official documentation for ID Vision system.

remote_theme: jekyll/minima@v3.0.0

plugins:
  - jekyll-remote-theme

minima:
  skin: dark
  header_pages: []
  footer_pages:
    - about.md
